name: Bug Report
description: Report a defect in runtime behavior, policy flow, or integration.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Exact deterministic steps and inputs.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
    validations:
      required: true
  - type: input
    id: policy
    attributes:
      label: Policy Set/Version
      placeholder: finance / v17
  - type: textarea
    id: artifacts
    attributes:
      label: Logs / Artifacts
      description: Include decision_id, escrow_id, replay output, and relevant metrics if available.
